#!/bin/sh
set -e 
PATH="$HOME/.local/bin:/usr/local/bin:$PATH"
$DIR="sade/src/dart/Dart"
trap 'rm -f "$DIR/tags.$$"' EXIT

# Assumes universal-ctags is on the path
pushd .
cd $DIR
#ctags --tag-relative=yes -R -f tags.$$ --languages=-javascript,sql
ctags -R -f tags.$$
mv tags.$$ tags
popd
